### ISSUE TITLE
Criação de pipeline com validação

### ISSUE THREAD

**Issue by somatorio** [mentoriaiac/iac-modulo-cloudflare#2]
No momento o módulo não possui validação automatizada, o que requer validação manual antes de qualquer pr ser aprovada e não garante o estado funcional do trunk

Para isto precisamos criar uma pipeline que faça ao menos a validação estática do código terraform

**Comment by klebercabral** [comment]
fiz o fork e criei o workflow do CI para esta Issue
gostaria de agendar para amanhã (06/04/2021) as 19:00 mostrar como fiz para vocês no Discord

**Comment by gomex** [comment]
Valeu @klebercabral ! Muito bom!
